# *** This Dockefile is generated by KloverCloud. You can modify it based on your application requirements *** #

FROM container-registry.console.klovercloud.com/klovercloud/openjdk:8-jdk
RUN useradd -ms /bin/bash klovercloud
WORKDIR /home/klovercloud

COPY --from=build target/BasicJWTSecurity-0.1.0.jar app.jar

EXPOSE 8080

EXPOSE 8081

USER klovercloud

ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=$SPRING_PROFILE -jar /home/klovercloud/app.jar

